In [3]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import *
from keras.models import Sequential
from keras.layers import *
import re
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
okt = Okt()

# 데이터 불러오기

In [4]:
df = pd.read_csv('news_titles.csv')
df

title  category
0                       윤석열 與 작심비판 에 이낙연 김부겸 온도차  politics
1                      술렁이는 민심 움직이는 통합당 공세 쇄신 박차  politics
2                   5분 연설 윤희숙 국토장관 넘어 서울시장 후보 거론  politics
3             단독 5분 연설 윤희숙 文 정권 비판 저서 인세 전액 기부 중  politics
4                 김근식 김두관의 윤석열 공격 PK 맹주 노리는 헛발질   politics
5             통합당이 여당인줄 수해 현장 달려가고 지원금 인상도 먼저 발표  politics
6                   원희룡 추미애 사과 해라 윤석열 찍어내기 특검해야   politics
7                       與 지지율 하락세 촉각 당내 독주 탓 지적도  politics
8                  통합당 검언유착 특검 국조 주호영 그야말로 권언유착   politics
9                  존경하는 의원님께 여의도로 띄우는 이재명의 친서 정치  politics
10             부동산에 발목 잡힌 민주당 지지율 통합당 골든크로스 나타날까  politics
11            류호정 저리가라는 홍준표 꽃무늬 셔츠 진중권 洪 정도는 돼야   politics
12     통합당 0 8 p 차 추격 민주당 술렁 정신차리자 부터 일희일비 말자 까지  politics
13               남북 작은 교역 물꼬틀까 北 술 南 설탕 물물교환 코 앞  politics
14         단독 만나자 공문 보낸 의협에 복지부 부터 만나라 결론 내린 총리실  politics
15             靑 文 사저 부지 농지법 위반 아냐 김정숙 여사가 비료 줬다  politics
16             17년전 빽바지 도 원로의 지지 있었다 원피스 응원하는 국회  politics
17                        정총리 의암댐 선박 전복 현장 긴급 방문  politics
18                    상승세 탄 통합당 지도부는 원내투쟁 전략 굳히기  politics
19                  저는 임차인 용혜인 연설에 김태년이 보낸 깜짝 선물  politics
20                      윤석열 與 작심비판 에 이낙연 김부겸 온도차  politics
21                     술렁이는 민심 움직이는 통합당 공세 쇄신 박차  politics
22                  5분 연설 윤희숙 국토장관 넘어 서울시장 후보 거론  politics
23            단독 5분 연설 윤희숙 文 정권 비판 저서 인세 전액 기부 중  politics
24                김근식 김두관의 윤석열 공격 PK 맹주 노리는 헛발질   politics
25            통합당이 여당인줄 수해 현장 달려가고 지원금 인상도 먼저 발표  politics
26                  원희룡 추미애 사과 해라 윤석열 찍어내기 특검해야   politics
27                      與 지지율 하락세 촉각 당내 독주 탓 지적도  politics
28                 통합당 검언유착 특검 국조 주호영 그야말로 권언유착   politics
29                 존경하는 의원님께 여의도로 띄우는 이재명의 친서 정치  politics
...                                          ...       ...
25774                      삼성 이재용 시간이 없다 기술혁신 강조        it
25775                    적자 개선 LG폰 보급형 5G로 매출 확대        it
25776                 애플에 울고 웃은 삼성 LG 하반기 모두 웃는다        it
25777             이대로 두면 넷플릭스에 국내 콘텐츠 생태계 다 내준다         it
25778             KBS 경영혁신안 조합원 설문조사 가장 우려되는 정책은        it
25779        GC녹십자 2분기 영업이익 156억원 작년 동기 대비 22 감소        it
25780         넷플릭스 받을까 KT 시즌 오픈 웨이브 대항 통합은 동상이몽         it
25781               쿠팡이 쏘아 올린 배달 전쟁 배민 요기요 본격 참전        it
25782                      MZ세대 중고품검색 품목 1위 아이폰         it
25783                    애플 코로나19 뚫고 아이폰 제때 내놓을까        it
25784             LG전자 스마트폰 포기 안해 2분기 매출 판매량 반등         it
25785              몸집 불리는 토종 OTT 이유는 하나 넷플릭스 견제         it
25786                        현대車 렌터카 3社와 데이터 동맹         it
25787            페이 클라우드 웹툰 고맙다 네이버 2분기 역대 최고 매출        it
25788            넥슨 대규모 경력직 채용 신규 개발사發 프로젝트 본궤도         it
25789                     비대면에 쇼핑 광고 약진 네이버 최대매출        it
25790          미디어 주권 잃을 위기 국내 OTT 규제보단 진흥정책 필요         it
25791              유심칩 털어봐야 별게 없는데 정진웅은 왜 몸을 날렸나        it
25792                  1회 검사로 코로나 무증상 감염도 100 판정        it
25793          쇼핑 끌고 페이 웹툰 밀고 네이버 매출 1 9조원 사상 최대        it
25794         화웨이 폰 삼성 제치고 세계 1위 10대 중 7대 中서 판매         it
25795                        바보야 진짜 문제는 넷플릭스가 아냐        it
25796   이연모號 LG폰 파격 변신 통했나 코로나19에도 2분기 실적 개선 종합         it
25797               롯데카드 IBM 금융권의 클라우드 도입 이젠 현실         it
25798     라인플러스 연말까지 최적 근무형태 찾자 IT 업계는 재택근무 실험 중        it
25799                    햇빛으로 바닷물을 100 먹는 물로 바꾼다        it
25800            국정원 과학정보본부 3차장제 승격에 보안업계 기대감 솔솔        it
25801                      LG전자 스마트폰 벨벳 주도 실적 선방        it
25802               배차음모론 휘말린 배달의민족 라이더 1000명 수혈        it
25803                    CJ ENM 티빙 분사 10월 1일로 연기        it

[25804 rows x 2 columns]

# 원핫인코딩, 학습검증데이터분류

In [5]:
X = df['title']
Y = df['category']

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 레이블 인코딩
# encoder = LabelEncoder()
# encoder.fit(df['category'])
# df['category'] = encoder.transform(df['category'])
# df.category.nunique()
# encoder.classes_
encoder = LabelEncoder()
encoder.fit(Y)
encoder.inverse_transform([0,1,2,3,4,5])
Y = encoder.transform(Y)
#'culture', 'economic', 'it', 'politics', 'social', 'world'


#원핫인코딩
YoneHot = to_categorical(Y)
YoneHot

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

In [14]:
t = okt.morphs(X[0])
t

['윤석열', '與', '작심', '비판', '에', '이낙연', '김부겸', '온도', '차']

In [11]:
token = Tokenizer()
token.fit_on_texts(t)
Xtoken = token.texts_to_sequences(t)
Xtoken

[[1], [2], [3], [4], [5], [6], [7], [8], [9]]

In [5]:
token = Tokenizer()
token.fit_on_texts(X)
Xtoken = token.texts_to_sequences(X)
Xtoken

[[30, 34, 5127, 51, 146, 152, 3594],
 [12435, 798, 4496, 26, 5128, 12436, 1154],
 [749, 502, 47, 7257, 240, 2165, 714, 1701],
 [37, 749, 502, 47, 503, 988, 275, 7258, 12437, 12438, 1903, 11],
 [1376, 12439, 30, 313, 3239, 5992, 2943, 9195],
 [3595, 12440, 388, 139, 12441, 2944, 12442, 950, 163],
 [2166, 157, 397, 7259, 30, 7260, 7261],
 [34, 440, 3596, 1702, 9196, 885, 422, 5129],
 [26, 153, 3597, 5993, 212, 12443, 886],
 [9197, 12444, 12445, 7262, 5130, 12446, 604],
 [3240, 2945, 5994, 61, 440, 26, 9198, 12447],
 [196, 12448, 4029, 9199, 9200, 263, 12449, 5995, 2946],
 [26, 213, 69, 1377, 513, 2036, 61, 4497, 12450, 4030, 12451, 4498, 750],
 [3241, 2320, 9201, 12452, 185, 1104, 5131, 5132, 5996, 4499, 1212],
 [37, 7263, 9202, 1607, 5997, 1522, 4030, 12453, 1446, 1213, 7264],
 [504, 503, 4500, 771, 4501, 751, 207, 12454, 12455, 9203, 5133],
 [7265, 4502, 476, 12456, 924, 772, 353, 9204, 124],
 [5998, 2321, 398, 925, 139, 441, 442],
 [1608, 3598, 26, 9205, 5134, 1447, 3599],
 [1155, 364

In [6]:
max = 0
for i in range(len(Xtoken)):
    if(max<len(Xtoken[i])):
        max = len(Xtoken[i])    
max

26

In [7]:
Xpad = pad_sequences(Xtoken,26)
Xpad

array([[    0,     0,     0, ...,   146,   152,  3594],
       [    0,     0,     0, ...,  5128, 12436,  1154],
       [    0,     0,     0, ...,  2165,   714,  1701],
       ...,
       [    0,     0,     0, ...,  1505,   287,  1252],
       [    0,     0,     0, ...,  6794,  4965, 15670],
       [    0,     0,     0, ...,  1714, 15589,   273]])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
Xtrain,Xval,Ytrain,Yval = train_test_split(Xpad,YoneHot,test_size=0.2,random_state=807)

In [10]:
wordsize= len(token.word_index)+1

In [11]:
wordsize

48281

In [12]:
model = Sequential()
model.add(Embedding(wordsize,300))
model.add(LSTM(100,activation='tanh'))
model.add(Flatten())
model.add(Dense(6,activation='softmax'))

In [14]:
word_index = token.word_index
word_index

{'종합': 1,
 '피해': 2,
 '코로나': 3,
 '코로나19': 4,
 '서울': 5,
 '부동산': 6,
 '등': 7,
 '사망': 8,
 '정부': 9,
 '폭우': 10,
 '중': 11,
 '또': 12,
 '것': 13,
 '더': 14,
 '비': 15,
 '왜': 16,
 '트럼프': 17,
 '만에': 18,
 '美': 19,
 '실종': 20,
 '한동훈': 21,
 '확진': 22,
 '최대': 23,
 '전': 24,
 '통제': 25,
 '통합당': 26,
 '첫': 27,
 '논란': 28,
 '우려': 29,
 '윤석열': 30,
 '안': 31,
 '아파트': 32,
 '경찰': 33,
 '與': 34,
 '추가': 35,
 '수위': 36,
 '단독': 37,
 '의혹': 38,
 '확진자': 39,
 '물폭탄': 40,
 '이': 41,
 '중국': 42,
 '검찰': 43,
 'vs': 44,
 '한': 45,
 '공급': 46,
 '윤희숙': 47,
 '3명': 48,
 '틱톡': 49,
 '충북': 50,
 '에': 51,
 '1명': 52,
 '못': 53,
 '박원순': 54,
 '월세': 55,
 '최고': 56,
 '수도권': 57,
 '곳곳': 58,
 '침수': 59,
 '집값': 60,
 '민주당': 61,
 '산사태': 62,
 '수사': 63,
 '中': 64,
 '속': 65,
 '1': 66,
 '2분기': 67,
 '2명': 68,
 '8': 69,
 '부산': 70,
 '없다': 71,
 '시장': 72,
 '삼성': 73,
 '경기': 74,
 '오늘': 75,
 '구속': 76,
 '주민': 77,
 '중부': 78,
 '중단': 79,
 '서울시': 80,
 '속출': 81,
 '내': 82,
 '성추행': 83,
 '도로': 84,
 '국내': 85,
 '감염': 86,
 '전세': 87,
 '집중호우': 88,
 '방류': 89,
 '다시': 90,
 '듯': 91,
 '미국': 9

In [23]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [24]:
history = model.fit(Xtrain,Ytrain,batch_size=100,epochs=10,validation_data=(Xval,Yval))

Epoch 1/10
207/207 [==============================] - 37s 180ms/step - loss: 1.0547 - accuracy: 0.6257 - val_loss: 0.7599 - val_accuracy: 0.7380
Epoch 2/10
207/207 [==============================] - 36s 174ms/step - loss: 0.3641 - accuracy: 0.8812 - val_loss: 0.7700 - val_accuracy: 0.7497
Epoch 3/10
207/207 [==============================] - 36s 174ms/step - loss: 0.1106 - accuracy: 0.9655 - val_loss: 0.9636 - val_accuracy: 0.7334
Epoch 4/10
207/207 [==============================] - 36s 176ms/step - loss: 0.0475 - accuracy: 0.9842 - val_loss: 1.1090 - val_accuracy: 0.7314
Epoch 5/10
207/207 [==============================] - 37s 177ms/step - loss: 0.0277 - accuracy: 0.9905 - val_loss: 1.1814 - val_accuracy: 0.7283
Epoch 6/10
207/207 [==============================] - 37s 181ms/step - loss: 0.0198 - accuracy: 0.9936 - val_loss: 1.3721 - val_accuracy: 0.7183
Epoch 7/10
207/207 [==============================] - 37s 180ms/step - loss: 0.0145 - accuracy: 0.9955 - val_loss: 1.4784 - val_ac

In [74]:
sentence = "K웹툰 잘나가네…카카오 '픽코마' 日 앱 매출 1위"
# sentence = 'KT, 2분기 AI/DX 분야에서 웃었지만…5G·미디어 성장 미미'
hangul = re.compile('[^0-9a-zA-Zㄱ-힗]+')
sentence = hangul.sub(" ",sentence)
sentence

'K웹툰 잘나가네 카카오 픽코마 日 앱 매출 1위'

In [75]:
sentence = token.texts_to_sequences([sentence])
sentence

[[19553, 23203, 360, 23685, 98, 1250, 188, 119]]

In [76]:
len(sentence)

1

In [77]:
sent_pad = pad_sequences(sentence,26)
sent_pad

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
        19553, 23203,   360, 23685,    98,  1250,   188,   119]])

In [78]:
answer = ['3']

In [79]:
np.argmax(model.predict(sent_pad))

4

In [ ]:
#'culture', 'economic', 'it', 'politics', 'social', 'world'